### 로그인
POST http://133.186.241.167:8200/login
Content-Type: application/json

{
  "username": "nhnacademy",
  "password": "nhnacademy12345*"
}

### index (인증 테스트)
GET localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MzYxMzQ4MzUsImV4cCI6MTczNjIyMTIzNX0.8O5xE1pY0ka9aX-TA4rnqA3tHBwAR4_E8-P9WhtBkMg

### 객실조회
GET http://localhost:8080/v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MTA1MTIyMDgsImV4cCI6MTc5NjkxMjIwOH0.-sx5W47k7xEI24iTPSSFUzxOH8LNLzboDjmJlqykPkE
Content-Type: application/json


### 객실생성
POST http://localhost:8080/v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MTA1MTIyMDgsImV4cCI6MTc5NjkxMjIwOH0.-sx5W47k7xEI24iTPSSFUzxOH8LNLzboDjmJlqykPkE
Content-Type: application/json

{
  "name": "...",
  "capacity": 2,
  "floor": 3,
  "hasBathtub": true,
  "viewType": "oceanView"
}

###
POST localhost:8080/v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MTA1MTIyMDgsImV4cCI6MTc5NjkxMjIwOH0.-sx5W47k7xEI24iTPSSFUzxOH8LNLzboDjmJlqykPkE
Content-Type: application/json

{
    "name" : "unique",
    "capacity" : 200000000000,
    "floor" : 3,
    "hasBathtub" : true,
    "viewType" : "cityView"
}